#!/bin/bash
#SBATCH --job-name=Nelms2019_Salmon
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --time=72:00:00
#SBATCH --mem=120gb
#SBATCH --output=nelms2019.%j.out
#SBATCH --error=nelms2019.%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=tms51355@uga.edu

module load Salmon/1.9.0-gompi-2020b

salmon alevin -l ISR --whitelist nelms2019_bc.txt --umi-geometry 1[1-10] --bc-geometry 1[11-18] --read-geometry 2[7-end] -i transcriptome_index -1 SRR7989734_2.fastq.gz SRR7989735_2.fastq.gz SRR7989736_2.fastq.gz S$


#changes in this script is using the Nelms2019 barcodes (also in github) -- labeled as nelms2019_bc.txt in GACRC 
# switch the reads, read _1 has the cell barcodes, read _2 has the actual reads 



